### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by sitysat** [sitysat/SEBC#16]
As user raffles, use teragen to generate a 51,200,000-record dataset into eight files

**Comment by sitysat** [comment]
done
https://github.com/sitysat/SEBC/blob/master/SEBC-master/challenges/labs/4_teragen.md

**Comment by mfernest** [comment]
`4_teragen.md` - your job did not produce eight output files, possibly because this cluster also ran in LocalJobRunner mode.

INC
