### ISSUE TITLE
YARN/RM Lab

### ISSUE THREAD

**Issue by sitysat** [sitysat/SEBC#7]
Navigate to the Static Service Pools page

- Capture the Status and Service Usage sidebars to resources/labs/2_service_usage.png

On the Configuration tab, allocate 10% to HDFS and 90% to YARN

- If you installed other services such as HBase or Impala, delete them first
- Complete the wizard and restart your cluster

Confirm the settings after the restart

**Comment by sitysat** [comment]
Configure static resource pool and capture current resource status

**Comment by sitysat** [comment]
edit YARNTest.sh

**Comment by sitysat** [comment]
All jobs is done

**Comment by sitysat** [comment]
result
https://github.com/sitysat/SEBC/tree/master/SEBC-master/resources/labs

**Comment by mfernest** [comment]
👍
