### ISSUE TITLE
CM Monitoring Lab

### ISSUE THREAD

**Issue by sitysat** [sitysat/SEBC#9]
start do monitoring lab

**Comment by sitysat** [comment]
start using the API on the command line to:

- Report the latest available version of the API

- Report the CM version

- List all CM users

- Report the database server in use by CM

**Comment by sitysat** [comment]
done

**Comment by sitysat** [comment]
result
https://github.com/sitysat/SEBC/tree/master/SEBC-master/enterprise/labs

**Comment by mfernest** [comment]
👍
